version: '3'
services:
  app:
    build: 
      context: .
    volumes:
      - .:/home
    ports:
      - 3000:3000
    image: products_home:1.0
    container_name: products_home
    command: pnpm serve --host 0.0.0.0

